@startuml
VC管理アプリ -> VC管理アプリ : マイナンバーカードを使って\nデータを署名する
VC管理アプリ -> マイナンバーAPI : マイナンバーカードの情報が\n書いてあるVCの発行を依頼
note left: リクエストにはマイナンバーカードの\n秘密鍵で署名されたデータ
マイナンバーAPI -> マイナンバーAPI : 保存してある利用者の\n公開鍵で署名を検証
マイナンバーAPI -> マイナンバーAPI : マイナンバーカードの\n情報をVC化して署名
マイナンバーAPI -> VC管理アプリ : マイナンバー情報VC発行
note left: マイナンバー情報VC
VC管理アプリ -> VC管理アプリ : マイナンバーVCからVPを生成
VC管理アプリ -> 運転免許発行 : 運転免許発行依頼
note right: マイナンバー情報VP
運転免許発行 -> 運転免許発行 : 資格が存在するか確認
運転免許発行 -> VC管理アプリ : 運転免許VC発行
note left: 運転免許VC
VC管理アプリ -> VC管理アプリ : 運転免許VCからVPを生成
VC管理アプリ -> レンタカー屋 : 認証＋サービス利用依頼
note right: 運転免許VP
レンタカー屋 -> レンタカー屋 : VPを検証することで認証
レンタカー屋 -> レンタカー屋 : 空きの車を確認
レンタカー屋 -> VC管理アプリ : 認証OK、ある期間のレンタル資格VC発行
note left: ある期間のレンタル資格VC
@enduml
